name: Android CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name if different.

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can use '11', 'adopt@1.11', or 'temurin@11' here.
          distribution: 'adopt'  # Replace with 'adopt' or 'temurin' based on your preference.

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Tests
        run: ./gradlew testDebug

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
